# This is a basic workflow to help you get started with Actions

name: "Validate and Export"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        
      - name: Install ADF package
        run: npm install
        working-directory: ./build
      
      - name: Validate
        run: npm run build validate ${GITHUB_WORKSPACE} /subscriptions/4e4653fe-8540-4bea-86d1-a5a193480a63/resourceGroups/ess-adf-gh-rg/providers/Microsoft.DataFactory/factories/ess-adf-gh
        working-directory: ./build

      - name: Export
        run: npm run build export ${GITHUB_WORKSPACE} /subscriptions/4e4653fe-8540-4bea-86d1-a5a193480a63/resourceGroups/ess-adf-gh-rg/providers/Microsoft.DataFactory/factories/ess-adf-gh "ArmTemplate"
        working-directory: ./build
        
      - name: Upload ARM Template as Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ArmTemplate
          path: ./build/ArmTemplate

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          prerelease: true
          files: ./build/ArmTemplate
